### ISSUE TITLE
Style bootstrap don'work

### ISSUE THREAD

**Issue by devemtv** [wewowweb/laravel-svelte-preset#15]
Hello! I try create custom components, but my components losse styles botstrapp. Sorry my english.

here my code...
`mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .svelte({
        customElement: true,
        tag: null,
    });`

**Comment by morpheus7CS** [comment]
Hey @devmiguelt,

first of all, no apologies needed for your English. My Spanish is not any good either :wink:

As Svelte has scoped styles, the fastest way to get around this is to include the CSS file inside your custom component like so:

```js
<style>  
@import "/css/app.css";  
</style>  
```
Hope that helps!

Kind regards,
g
