### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by Kidcredo** [wewowweb/laravel-svelte-preset#16]
Not sure how to make this work in Laravel 8

**Comment by morpheus7CS** [comment]
Hey @Kidcredo,

sorry for a late response. We will add Laravel 8 support tonight.

Kind regards,
g

**Comment by morpheus7CS** [comment]
Hey @Kidcredo,

sorry for the long wait. The [v0.1.8](https://github.com/wewowweb/laravel-svelte-preset/releases/tag/v0.1.8) now comes with Laravel 8 support.

Kind regards,
g

**Comment by Kidcredo** [comment]
Hey @morpheus7CS Thanks a lot.
