### ISSUE TITLE
Uncaught TypeError: options is undefined when using custom component

### ISSUE THREAD

**Issue by SirMishaa** [wewowweb/laravel-svelte-preset#18]
Hello ! 

I'm getting this error (Uncaught TypeError: options is undefined) when I use a custom component. 

Am I doing something wrong?

app.js : 
```js
import HelloSvelte from "./Components/HelloSvelte.svelte";
customElements.define('hello-svelte', HelloSvelte)
```
hello.svelte : 
```svelte
<svelte:options tag="{null}" />

<script>
    export let name = 'world';
</script>

<h1>Hello {name}!</h1>
<slot></slot>
```
home.blade.php : 
```php
@extends('layouts.app')

@section('content')
    <hello-svelte></hello-svelte>
@endsection
```
And webpack.mix.js :
```js
mix.js('resources/js/app.js', 'public/js')
        .svelte({
            customElement: true,
        }).sourceMaps()
    .postCss('resources/css/app.css', 'public/css', [
        require('tailwindcss')
    ])
 ```
 
 ![image](https://user-images.githubusercontent.com/42717232/119075131-951e1b80-b9f0-11eb-8090-084a10750399.png)

**Comment by morpheus7CS** [comment]
Hey @SirMishaa,

would you mind sharing a few details on the version of your Laravel, Laravel Mix, Webpack, and the version of laravel-svelte-preset? 

I think you have done nothing wrong, but it seems that the error is tied to the Webpack v5 removing the legacy pollyfills. For a quick fix, you can try modifying the webpack.mix.js from the one you have now, like so:

```diff
mix.js('resources/js/app.js', 'public/js')
        .svelte({
            customElement: true,
        })
+   .options({legacyNodePolyfills: true})  
    .sourceMaps()
    .postCss('resources/css/app.css', 'public/css', [
        require('tailwindcss')
    ])
```

You may also have to run `npm install && npm run dev` just to be on the safe side with installations.

Let me know if that solves your issue.

Kind regards,
g
