### ISSUE TITLE
There is Conflicts between Laravel-mix 4.x and 6.0 is not running npm run dev

### ISSUE THREAD

**Issue by Aminur670** [wewowweb/laravel-svelte-preset#21]

**Comment by morpheus7CS** [comment]
Hey @Aminur670,

we have just added a special rule in the underlying laravel-mix-svelte dependency and the [v0.2.0](https://github.com/wewowweb/laravel-svelte-preset/releases/tag/v0.2.0) version we have just tagged, should solve the issues.

I'm closing the issue, but feel free to reopen it if the problem persists.

Kind regards,
g
