### ISSUE TITLE
npm run dev "laravel-mix": "^6.0.6" is not working

### ISSUE THREAD

**Issue by ingesoftllc** [wewowweb/laravel-svelte-preset#22]
this error is reported by th console 
[webpack-cli] TypeError: Cannot read property 'babel' of undefined

**Comment by morpheus7CS** [comment]
Hey @ingesoftllc,

we have just added a special rule in the underlying laravel-mix-svelte dependency and the [v0.2.0](https://github.com/wewowweb/laravel-svelte-preset/releases/tag/v0.2.0) version we have just tagged, should solve the issues.

I'm closing the issue, but feel free to reopen it if the problem persists.

Kind regards,
g
