### ISSUE TITLE
Please enable this package to work with PHP 8.1

### ISSUE THREAD

**Issue by MichaelNZ85** [wewowweb/laravel-svelte-preset#24]
I am using Laravel 8.75 with PHP 8.1.1 installed on my MacBook Pro, and I get the following error when trying to install this package:

`[InvalidArgumentException]                                                                                                        
  Package wewowweb/laravel-svelte-preset has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - wewowweb/laravel-svelte-preset v0.2.0 requires php ^7.2 which does not match your installed version 8.1.1.  
 `

It would be great if you could update this package to work with PHP 8.1.

**Comment by n-osennij** [comment]
+1

**Comment by RoNoLo** [comment]
+1

**Comment by magic-thomas** [comment]
+1

**Comment by thmr** [comment]
+1

**Comment by morpheus7CS** [comment]
Hey to all of you,

sorry for this one taking so long. It should have been fixed with the [v0.2.1 - 2021-06-02](https://github.com/wewowweb/laravel-svelte-preset/releases/tag/v0.2.1) release.

Kind regards,
g
