### ISSUE TITLE
Support for Laravel 6 is unavailable

### ISSUE THREAD

**Issue by daimekashiya** [wewowweb/laravel-svelte-preset#3]
Hi, just to inform that as at the date of this issue was generated, this package did not support the latest version of Laravel (as at Laravel version 6.0.1). below are the terminal input and output during the installation of the package to a Laravel version 6.0.1 project for your reference : 

$ composer require wewowweb/laravel-svelte-preset
Using version ^0.1.2 for wewowweb/laravel-svelte-preset
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wewowweb/laravel-svelte-preset ^0.1.2 -> satisfiable by wewowweb/laravel-svelte-preset[v0.1.2].
    - Conclusion: remove laravel/framework v6.0.1
    - Conclusion: don't install laravel/framework v6.0.1
    - wewowweb/laravel-svelte-preset v0.1.2 requires illuminate/support 5.8.* -> satisfiable by illuminate/support[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.0|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.11|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.12|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.14|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.15|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.17|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.18|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.19|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.2|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.20|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.22|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.24|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.27|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.28|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.29|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.3|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.30|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.31|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.32|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.33|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.34|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.35|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.4|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.8|don't install laravel/framework v6.0.1
    - don't install illuminate/support v5.8.9|don't install laravel/framework v6.0.1
    - Installation request for laravel/framework (locked at v6.0.1, required as ^6.0) -> satisfiable by laravel/framework[v6.0.1].

Appreciate your assistance to update the compatibility of this package. 
Thank you

**Comment by shuv1824** [comment]
For now you can install the [laravel-mix-svelte](https://www.npmjs.com/package/laravel-mix-svelte) npm package to manually make a Svelte scaffold in your Laravel 6 application.

**Comment by morpheus7CS** [comment]
Hey @daimekashiya,

this package should now be compatible with Laravel 6.x.

I will be closing the issue now, but do re-open it if the problems persist.

Kind regards,
g
