### ISSUE TITLE
svelte routes with laravel

### ISSUE THREAD

**Issue by moneebalalfi** [wewowweb/laravel-svelte-preset#5]
hey, this is very cool but why I cant use svelte links(**routes**) in blade.php pages ???****

**Comment by morpheus7CS** [comment]
Hey @moneebalalfi,

the package is meant as a starting point for people who would like to use Svelte and Laravel in a project. It is a very un-opinionated starting point and prefers not to make too many decisions as we don’t develop in Svelte enough to make those.

Svelte by default doesn’t have it’s own router. You can add one of the many packages that handles routing, but the routes will have to be (as far as I know) added inside a Svelte component file and not inside any of the blade.php files.

Kind regards,
g
